env:
  global:
      # Set these values
      - BUILD_COMMIT="maintenance/v1.16" #"v1.16.5" # "master"
      - TESTPYPI_UPLOAD=false # false
      - PYPI_UPLOAD=false # true
      - CONDA_BUILD=false
      - CONDA_UPLOAD=false
      - SDIST=false
      # These values should not usually change
      - REPO_DIR="randomgen"
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - BUILD_DEPENDS="Cython numpy"
      - TEST_DEPENDS="numpy pytest nose"
      - CONDA_NUMPY_VERSION=1.16

language: python
python: 3.6
sudo: required
dist: xenial
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - CONDA_NUMPY_VERSION=1.15
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - SDIST=true
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
        - CONDA_NUMPY_VERSION=1.15
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # Upload wheels/sdist to PyPI
    - source build-sdist.sh
    - source twine-upload.sh
    - source build-conda.sh
