skip_tags: true
clone_depth: 1000

# We always use a 64-bit machine, but can build x86 distributions
# with the PYTHON_ARCH variable.
platform: x64
os: Visual Studio 2015

matrix:
    fast_finish: false

environment:
  global:
    BUILD_COMMIT: "v1.20.1"
    TESTPYPI_UPLOAD: "false" # "false"
    PYPI_UPLOAD: "true" # "true"
    REPO_DIR: randomgen
    PACKAGE_NAME: randomgen
    PIP_PACKAGES: "pytest pytest-xdist"
  TESTPYPI_USERNAME:
    secure: 9D67F9Bcy8PITwg1cezOgw==
  TESTPYPI_PASSWORD:
    secure: sEkgnJNTN/bQu3Lh8PysOA==
  PYPI_USERNAME:
    secure: 9D67F9Bcy8PITwg1cezOgw==
  PYPI_PASSWORD:
    secure: ufGrse+xSx3blI6bh9bnSg==

  matrix:
    - PYTHON: C:\Python39-x64
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 64
      NUMPY_VER: 1.19.5

    - PYTHON: C:\Python39
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 32
      NUMPY_VER: 1.19.5

    - PYTHON: C:\Python38-x64
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 64
      NUMPY_VER: 1.17.5

    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64
      NUMPY_VER: 1.16.6

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
      NUMPY_VER: 1.16.6

    - PYTHON: C:\Python38
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 32
      NUMPY_VER: 1.17.5

    - PYTHON: C:\Python37
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32
      NUMPY_VER: 1.16.6

    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32
      NUMPY_VER: 1.16.6


install:
  - git submodule update --init --recursive
  - git config --global core.autocrlf false
  - git fetch --tags

  # Install new Python if necessary
  - ps: .\multibuild\install_python.ps1

  # Set path
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  - python -m pip install -U pip
  - pip install numpy==%NUMPY_VER% cython nose pytest pytest-xdist wheel
  - set "WHEELBUILDER_DIR=%cd%"

build_script:
  - cd %REPO_DIR%
  - git checkout %BUILD_COMMIT%
  - python setup.py bdist_wheel
  - cd ..

test_script:
  # install from wheel
  - pip install --pre --no-index --find-links %REPO_DIR%\dist\ %PACKAGE_NAME%
  - mkdir _for_testing
  - cd _for_testing
  - python -c "import randomgen; randomgen.test(extra_args=['--skip-slow', '-n=2'])"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: $(REPO_DIR)\dist\*

on_success:
  - echo "Upload here"
  - cd %WHEELBUILDER_DIR%\
  - pip install twine
  - call twine-upload.bat
