{% set name = "randomgen" %}
{% set version = "v1.16.5" %}
{% set sha = "959ef3af6756552ae894215bde420255ad8c12b973c33ea75fa768b0e98631b9" %}
package:
    name: {{ name|lower }}
    version:  {{ version }}

source:
    version: {{ version }}
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version[1:] }}.tar.gz
    sha256: {{ sha }}

build:
    number: 0
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python
        - pip
        - cython
        - numpy
    run:
        - python
        - {{ pin_compatible('numpy') }}

test:
    requires:
        - pytest
        - nose

about:
    home: 'https://github.com/bashtage/randomgen'
    license: NSCA
    license_file: LICENSE.md
    summary: Replacement random number generator for NumPy
