package:
    name: randomgen
    version: v1.15.1
source:
    version: v1.15.1
    git_url: 'https://github.com/bashtage/randomgen.git'
build:
    number: 0
requirements:
    build:
        - python
        - setuptools
        - cython
        - 'numpy x.x'
    run:
        - python
        - 'numpy x.x'
test:
    requires:
        - pytest
        - nose
about:
    home: 'https://github.com/bashtage/randomgen'
    license: NSCA
